spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    initialization-mode: always
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  cache:
    type: redis
    redis:
      host: localhost
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  observations:
    key-values:
      application: product-service
  tracing:
    sampling:
      probability: '1.0'
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: 'true'

loki:
  url: http://localhost:3100/loki/api/v1/push

server:
  port: 8002